<?php
define('PO_URL_SERVER', 'https://gateway.pagosonline.net/apps/gateway/index.html');
define('PO_URL_SERVER_TEST', 'https://gateway2.pagosonline.net/apps/gateway/index.html');

define('PO_URL_CONFIRMATION', 'admin/commerce/pagosonline/confirmation');
define('PO_URL_RESPONSE', 'admin/commerce/pagosonline/response');
define('PO_DESCRIPTION', 'commerce virtual store purchase order number @order_id');

define('PO_UID', 2);
define('PO_ENCRYPTION_KEY', '1111111111111111');
define('PO_ALIAS', 'PO-');

/**
 * Implements hook_permission().
 */
function commerce_pagosonline_permission() {
  $perm = array(
    'pagosonline settings' => array(
      'title' => 'Settings Pagos Online',
    ),
    'pagosonline detail transaction' => array(
      'title' => 'View Details Transaction',
    ),
  );
  return $perm;
}

/**
 * Implements hook_menu().
 */
function commerce_pagosonline_menu() {
  $menu = array();
  $menu['admin/commerce/pagosonline/response/%order/%/%'] = array(
    'page callback' => 'commerce_pagosonline_response',
    // $order_id, $sale_reference, $option
    'page arguments' => array(4),
    'access callback' => array('commerce_pagosonline_access_response'),
    'access arguments' => array(4, 5, 6),
    'type' => MENU_CALLBACK,
    'file' => 'commerce_pagosonline.inc',
  );
  $menu['admin/commerce/pagosonline/confirmation/%order/%/%'] = array(
    'page callback' => 'commerce_pagosonline_confirmation',
    // $order_id, $sale_reference, $option
    'page arguments' => array(2, 3, 4),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'commerce_pagosonline.inc',
  );
  $menu['admin/commerce/pagosonline/transaction/view/%/%'] = array(
    'page callback' => 'commerce_pagosonline_transaction_view',
    'page arguments' => array(3),
    'access callback' => TRUE,
    //'access callback' => 'commerce_pagosonline_transaction_view_validate',
    //'access arguments' => array(3, 4),
    'type' => MENU_CALLBACK,
    'file' => 'commerce_pagosonline_transaction.inc',
  );
  return $menu;
}
/**
 * Access page response
 */
function commerce_pagosonline_access_response($order, $token, $option) {
  $param = pagosonline_get_param($_GET);
  return  $option == commerce_pagosonline_get_md5($order->order_id, $token, 'RESPONSE');
}
/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_pagosonline_commerce_payment_method_info() {
  $payment_methods = array();
  $payment_methods['pagosonline'] = array(
    'base' => 'commerce_pagosonline',
    'title' => t('Pagosonline pay by (Visa, Master Card, American Expres, Diners)'),
    'short_title' => t('PagosOnline'),
    'description' => t('Pagos Online Payments Standard'),
    'terminal' => FALSE,
    'offsite' => TRUE,
    'offsite_autoredirect' => FALSE,
  );
  return $payment_methods;
}

/**
 * Form Settings Pagos Online
 **/
function commerce_pagosonline_settings_form($settings = NULL) {
  //module_load_include('inc', 'commerce_pagosonline');
  $form = array();
  $form['po_uid'] = array(
    '#title' => t('The number of user'),
    '#description' => t('The number of user in the system Pagosonline.net'),
    '#type' => 'textfield',
    '#size' => 12,
    '#default_value' => isset($settings['po_uid']) ? $settings['po_uid'] : PO_UID,
    '#required' => TRUE,
  );
  $form['po_encryption_key'] = array(
    '#title' => t('Encryption key'),
    '#type' => 'textfield',
    '#default_value' => isset($settings['po_encryption_key']) ? $settings['po_encryption_key'] : PO_ENCRYPTION_KEY,
    '#size' => 50,
    '#required' => TRUE,
  );
  $form['po_action_url'] = array(
    '#title' => t('Path Form Action'),
    '#type' => 'textfield',
    '#size' => 50,
    '#default_value' => isset($settings['po_action_url']) ? $settings['po_action_url'] : PO_URL_SERVER,
    '#required' => TRUE,
  );
  $form['po_action_url_test'] = array(
    '#title' => t('Test Path Form Action'),
    '#type' => 'textfield',
    '#size' => 50,
    '#default_value' => isset($settings['po_action_url_test']) ? $settings['po_action_url_test'] : PO_URL_SERVER_TEST,
    '#required' => TRUE,
  );

  $items = commerce_tax_rates();
  $options = array();
  foreach ($items as $name => $item) {
    $options[$name] = $item['title'];
  }

  $form['po_tax'] = array(
    '#title' => t('Tax Rate'),
    '#type' => 'select',
    '#size' => 5,
    '#multiple' => TRUE,
    '#options' => $options,
    '#default_value' => isset($settings['po_tax']) ? $settings['po_tax'] : '',
  );
  $form['po_alias'] = array(
    '#title' => t('Alias'),
    '#description' => t('Is concatenated with the order number, example: @example', array('@example' => '"' . @$settings['po_alias'] . '1"')),
    '#type' => 'textfield',
    '#size' => 20,
    '#default_value' => isset($settings['po_alias']) ? $settings['po_alias'] : PO_ALIAS,
  );

  $description = isset($settings['po_description']) ? $settings['po_description'] : PO_DESCRIPTION;

  $form['po_description'] = array(
    '#title' => t('Description'),
    '#description' => t('Pagosonline purchase description, use @order_id to obtain the order number'),
    '#type' => 'textfield',
    '#size' => 50,
    '#default_value' => $description,
    '#required' => TRUE,
  );
  $form['po_testing'] = array(
    '#title' => t('Test Enabled'),
    '#type' => 'select',
    '#options' => array(
      '0' => t('No'),
      '1' => t('Yes'),
    ),
    '#required' => TRUE,
    '#default_value' => isset($settings['po_testing']) ? $settings['po_testing'] : '',
  );

  return $form;
}

function commerce_pagosonline_submit_form($payment_method, $pane_values, $checkout_pane, $order) {

}
function commerce_pagosonline_redirect_form($form, &$form_state, $order, $payment_method) {
  $settings = $payment_method['settings'];
  dpm($settings);
  if (!isset($settings['po_uid']) || empty($settings['po_uid'])) {
    drupal_set_message(t('Pagos Online is not configured for use. No user Id has been specified.'), 'error');
    return array();
  }

  module_load_include('inc', 'commerce_pagosonline');

  $wrapper = entity_metadata_wrapper('commerce_order', $order);

  $settings['currency_code'] = $wrapper->commerce_order_total->currency_code->value();
  // Format: 1000.00
  $settings['amount'] = number_format($wrapper->commerce_order_total->amount->value(), 2, '.', '');

  // Tax
  $taxes = array(
    'base_price' => 0,
    'total' => 0,
  );

  $components = $wrapper->commerce_order_total->data->value();
  if (@$components['components']) {
    foreach ($components['components'] as $key => $component) {
      if ($component['name'] == 'base_price') {
        $taxes['base_price'] = $component['price']['amount'];
      }
      elseif (in_array($component['price']['data']['tax_rate']['name'], $settings['po_tax'])) {
        $taxes['total'] += $component['price']['amount'];
      }
    }
  }
  $settings['sale_reference'] = commerce_pagosonline_get_reference($settings['po_alias'], $order->order_id);

  $signature = commerce_pagosonline_get_firm($settings);

  $url_page = commerce_pagosonline_get_url($order->order_id);

  $form['#action'] = $settings['po_action_url'];

  $description = t($settings['po_description'], array(
    '@order_id' => $order->order_id,
  ));

  dpm($taxes);

  $data = array(
    'usuarioId' => $settings['po_uid'],
    'descripcion' => $description,
    'refVenta' => $settings['sale_reference'],
    'valor' => $settings['amount'],
    'baseDevolucionIva' => $taxes['base_price'],
    'iva' => $taxes['total'],
    'emailComprador' => $order->mail,
    'moneda' => $settings['currency_code'],
    'firma' => $signature,
    'url_confirmacion' => $url_page['confirmation'],
    'url_respuesta' => $url_page['response'],
    'extra1' => $payment_method['instance_id'],
  );
  // Mode Test
  if (@$settings['po_testing']) {
    dpm('Entro');
    $data['prueba'] = 1;
    $form['#action'] = $settings['po_action_url_test'];
  }

  foreach ($data as $name => $value) {
    $form[$name] = array(
      '#type' => 'hidden',
      '#value' => $value,
    );
  }

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Proceed to PagosOnline'),
  );
  return $form;
}
